{
  config,
  lib,
  pkgs,
  reaperLib,
  ...
}: let
  inherit (lib) concatMapStringsSep filterAttrs generators mapAttrs mkOption types;
  cfg = config.programs.reaper;

  bitfieldNumberType = types.mkOptionType {
    name = "bitfield number";
    description = "an unsigned integer bitfield contribution";
    check = value: builtins.isInt value && value >= 0;
    merge = _: definitions: builtins.foldl' (total: definition: total + definition.value) 0 definitions;
  };

  # bitfield INI types:
  bitfieldType = types.submodule {
    options = {
      mask = mkOption {
        type = bitfieldNumberType;
        description = "Bit mask to update.";
      };
      value = mkOption {
        type = bitfieldNumberType;
        description = "Masked bit value to write.";
      };
    };
  };

  # Reaper uses semicolon separated lists of strings and booleans
  # are always either zero or one
  formatIniValue = value:
    if builtins.isBool value
    then
      if value
      then "1"
      else "0"
    else if builtins.isList value
    then concatMapStringsSep ";" formatIniValue value
    else toString value;

  renderIni = sections:
    generators.toINI {} (builtins.mapAttrs (_: entries: builtins.mapAttrs (_: formatIniValue) entries) sections);

  renderBitfields = sections:
    generators.toINI {} (builtins.mapAttrs (_: entries: builtins.mapAttrs (_: entry: "${toString entry.mask}:${toString entry.value}") entries) sections);

  renderPayload = sections: bitfields:
    builtins.toJSON {
      sections = builtins.mapAttrs (_: entries: builtins.mapAttrs (_: formatIniValue) entries) sections;
      inherit bitfields;
    };

  nonEmptySections = filterAttrs (_: entries: entries != {}) cfg.ini.sections;

  nonEmptyFileSections =
    filterAttrs (_: sections: sections != {})
    (mapAttrs (_: sections: filterAttrs (_: entries: entries != {}) sections)
      cfg.ini.files);

  nonEmptyBitfieldSections = filterAttrs (_: entries: entries != {}) cfg.ini.bitfields;

  nonEmptyFileBitfieldSections =
    filterAttrs (_: sections: sections != {})
    (mapAttrs (_: sections: filterAttrs (_: entries: entries != {}) sections)
      cfg.ini.fileBitfields);

  emptyIniFile = pkgs.writeText "reaper-managed-empty.ini" "";
  emptyPayloadFile = pkgs.writeText "reaper-managed-empty.json" (renderPayload {} {});
in {
  options.programs.reaper.ini = {
    # Modules assign `programs.reaper.ini.sections.<section>.<key> = value`
    # when the target file is `reaper.ini`.
    sections = mkOption {
      type = types.attrsOf (types.attrsOf reaperLib.reaperTypes.iniValue);
      default = {};
      internal = true;
      description = "reaper.ini sections generated by preferences modules.";
    };

    # `programs.reaper.ini.files.<file>.<section>.<key> = value` when the target
    # is another mutable ini file, such as reapack.ini.
    files = mkOption {
      type = types.attrsOf (types.attrsOf (types.attrsOf reaperLib.reaperTypes.iniValue));
      default = {};
      internal = true;
      description = "Additional mutable INI files generated by scoped REAPER modules.";
    };

    bitfields = mkOption {
      type = types.attrsOf (types.attrsOf bitfieldType);
      default = {};
      internal = true;
      description = "Bitfield updates generated for mutable `reaper.ini` keys.";
    };

    fileBitfields = mkOption {
      type = types.attrsOf (types.attrsOf (types.attrsOf bitfieldType));
      default = {};
      internal = true;
      description = "Bitfield updates generated for additional mutable REAPER INI files.";
    };

    generatedFile = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      description = "Generated INI fragment merged into mutable `reaper.ini`.";
    };

    generatedFiles = mkOption {
      type = types.attrsOf types.path;
      internal = true;
      readOnly = true;
      description = "Generated INI fragments merged into mutable REAPER config files.";
    };

    emptyFile = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      description = "Empty INI fragment used for stale cleanup.";
    };

    generatedBitfieldFile = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      description = "Generated bitfield fragment merged into mutable `reaper.ini`.";
    };

    emptyBitfieldFile = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      description = "Empty bitfield fragment used for files without bitfield updates.";
    };

    generatedBitfieldFiles = mkOption {
      type = types.attrsOf types.path;
      internal = true;
      readOnly = true;
      description = "Generated bitfield fragments merged into mutable REAPER config files.";
    };

    generatedPayloadFile = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      description = "Generated JSON payload merged into mutable `reaper.ini`.";
    };

    emptyPayloadFile = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      description = "Empty JSON payload used for stale cleanup.";
    };

    generatedPayloadFiles = mkOption {
      type = types.attrsOf types.path;
      internal = true;
      readOnly = true;
      description = "Generated JSON payloads merged into mutable REAPER config files.";
    };

    writerPackage = mkOption {
      type = types.package;
      internal = true;
      readOnly = true;
      description = "Python INI writer used during activation.";
    };
  };
  config.programs.reaper.ini = {
    generatedFile = pkgs.writeText "reaper-managed.ini" (renderIni nonEmptySections);
    emptyFile = emptyIniFile;
    generatedBitfieldFile = pkgs.writeText "reaper-managed-bitfields.ini" (renderBitfields nonEmptyBitfieldSections);
    emptyBitfieldFile = pkgs.writeText "reaper-managed-empty-bitfields.ini" "";

    generatedFiles =
      {"reaper.ini" = cfg.ini.generatedFile;}
      // mapAttrs (_: _: emptyIniFile)
      nonEmptyFileBitfieldSections
      // mapAttrs
      (fileName: sections: pkgs.writeText "reaper-managed-${fileName}" (renderIni sections))
      nonEmptyFileSections;

    generatedBitfieldFiles =
      {"reaper.ini" = cfg.ini.generatedBitfieldFile;}
      // mapAttrs
      (_: _: cfg.ini.emptyBitfieldFile)
      nonEmptyFileSections
      // mapAttrs
      (fileName: sections: pkgs.writeText "reaper-managed-bitfields-${fileName}" (renderBitfields sections))
      nonEmptyFileBitfieldSections;

    generatedPayloadFile = pkgs.writeText "reaper-managed.json" (renderPayload nonEmptySections nonEmptyBitfieldSections);
    emptyPayloadFile = emptyPayloadFile;

    generatedPayloadFiles =
      mapAttrs
      (fileName: _: let
        sections =
          if fileName == "reaper.ini"
          then nonEmptySections
          else nonEmptyFileSections.${fileName} or {};
        bitfields =
          if fileName == "reaper.ini"
          then nonEmptyBitfieldSections
          else nonEmptyFileBitfieldSections.${fileName} or {};
      in
        pkgs.writeText "reaper-managed-${fileName}.json" (renderPayload sections bitfields))
      cfg.ini.generatedFiles;

    writerPackage = pkgs.writeShellApplication {
      name = "write-config";
      runtimeInputs = [pkgs.python3];
      text = ''exec python3 ${../scripts/write_config.py} "$@"'';
    };
  };
}
