{
  config,
  lib,
  ...
}: let
  inherit (lib) attrNames intersectLists mkOption types;
  cfg = config.programs.reaper;
  conflictingFiles = intersectLists (attrNames cfg.resourceFiles.files) (attrNames cfg.resourceLinks.files);
in {
  options.programs.reaper = {
    resourceFiles.files = mkOption {
      type = types.attrsOf types.path;
      default = {};
      internal = true;
      description = "Whole REAPER resource files generated by scoped modules.";
    };

    resourceLinks.files = mkOption {
      type = types.attrsOf (types.oneOf [types.path types.str]);
      default = {};
      internal = true;
      description = "Whole REAPER resource files symlinked from package outputs.";
    };

    resourceLinks.backupFileExtension = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Backup extension used before replacing existing regular REAPER resource
        files with symlinks. Set this explicitly, or set it to
        `config.home.backupFileExtension` in configurations where that Home
        Manager option exists.
      '';
    };
  };

  config.assertions = [
    {
      assertion = conflictingFiles == [];
      message = "REAPER resource files cannot be both generated and linked: ${builtins.concatStringsSep ", " conflictingFiles}";
    }
  ];
}
